#!/bin/bash

# Download the tarball from your Release
# MAKE SURE to replace this URL with your actual Release link!
wget -O data.tar "https://github.com/Duelly-Baxter/automated-foci-analysis/releases/download/data/data.tar"

# Extract the tarball into the 'data' folder
mkdir -p data
tar -xvf data.tar -C data/

# Create the results directory and set permissions
mkdir -p results
chmod -R 777 results

# Clean up the downloaded tar to save space
rm data.tar

echo "PostBuild Complete: Data extracted and results folder ready."
